[build]
  publish = "src"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Removing problematic plugins for now
# [[plugins]]
# package = "@netlify/plugin-lighthouse"
# 
# [[plugins]]
# package = "netlify-plugin-submit-sitemap"
# 
# [[plugins]]
<<<<<<< HEAD
# package = "netlify-plugin-image-optim"
=======
# package = "netlify-plugin-image-optim" 

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; script-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' data: https:; connect-src 'self'"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()" 
>>>>>>> development
