[build]
  publish = "src"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18" 

[[plugins]]
package = "@netlify/plugin-lighthouse"

[[plugins]]
package = "netlify-plugin-submit-sitemap"

[[plugins]]
package = "netlify-plugin-image-optim" 