[build]
  publish = "public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18" 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
package = "@netlify/plugin-lighthouse"

[[plugins]]
package = "netlify-plugin-submit-sitemap"

[[plugins]]
package = "netlify-plugin-image-optim" 