[build]
  publish = "public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Removing problematic plugins for now
# [[plugins]]
# package = "@netlify/plugin-lighthouse"
# 
# [[plugins]]
# package = "netlify-plugin-submit-sitemap"
# 
# [[plugins]]
# package = "netlify-plugin-image-optim" 

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; media-src 'self' https:; frame-src 'self' https://player.vimeo.com https://www.youtube.com;"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()" 